"""data import foundation

Revision ID: 20260718_0002
Revises: 20260718_0001
Create Date: 2026-07-18 16:52:29.180025

Additive migration for the data-import foundation: recipe versions, recipe
ingredients, provider-food cache, structured import errors, nutrition
provenance/coexistence, multi-source identity (``source_system``), and extra
import-run counters. No existing table or column is dropped.

Safety notes (this migration is written to be safe on a *non-empty* database,
not only the currently-empty dev database):

* New ``source_system`` columns are added ``NOT NULL`` with a server default of
  ``'unknown'`` so pre-existing rows are backfilled deterministically.
* New unique partial indexes on ``(parent, source_system, external_id) WHERE
  external_id IS NOT NULL`` could fail if a *pre-existing* table already held
  duplicate external ids under the backfilled ``'unknown'`` source system. The
  prior schema only enforced this for ``menu_items``; on any populated database
  those external ids must be deduplicated/backfilled before applying this
  revision. On an empty database there is nothing to reconcile.
* The ``nutrition_facts`` active-record uniqueness moves from ``(menu_item_id)``
  to ``(menu_item_id, provenance)``; existing active rows default to
  ``provenance = 'source_provided'`` and remain unique.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '20260718_0002'
down_revision: str | None = '20260718_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ENUM types added by this revision *via ALTER TABLE ... ADD COLUMN*. Unlike
# CREATE TABLE, ADD COLUMN does not auto-create the backing type, so these are
# created explicitly (checkfirst) before use and dropped in downgrade(). The
# enums that appear only inside CREATE TABLE below are auto-created by Alembic.
nutrition_provenance = postgresql.ENUM(
    'source_provided', 'recipe_calculated', 'manually_entered', 'estimated',
    name='nutrition_provenance', create_type=False,
)
nutrition_review_status = postgresql.ENUM(
    'not_required', 'needs_review', 'reviewed',
    name='nutrition_review_status', create_type=False,
)
calculation_status = postgresql.ENUM(
    'complete', 'partial', 'failed', name='calculation_status', create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    nutrition_provenance.create(bind, checkfirst=True)
    nutrition_review_status.create(bind, checkfirst=True)
    calculation_status.create(bind, checkfirst=True)

    op.create_table('provider_foods',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_food_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_grams', sa.Numeric(precision=12, scale=4), server_default='100', nullable=False),
    sa.Column('calories', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('carbohydrates_g', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('saturated_fat_g', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sugar_g', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cholesterol_mg', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_foods')),
    sa.UniqueConstraint('provider', 'provider_food_id', name='uq_provider_foods_provider_provider_food_id')
    )
    op.create_table('provider_food_portions',
    sa.Column('provider_food_id', sa.Uuid(), nullable=False),
    sa.Column('portion_description', sa.String(length=255), nullable=False),
    sa.Column('gram_weight', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_food_id'], ['provider_foods.id'], name=op.f('fk_provider_food_portions_provider_food_id_provider_foods'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_food_portions')),
    sa.UniqueConstraint('provider_food_id', 'portion_description', name='uq_provider_food_portions_provider_food_id_portion_description')
    )
    op.create_index('ix_provider_food_portions_provider_food_id', 'provider_food_portions', ['provider_food_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('data_import_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'error', name='import_error_severity'), nullable=False),
    sa.Column('stage', sa.Enum('fetch', 'validate', 'classify', 'normalize', 'parse_recipe', 'resolve_ingredient', 'calculate_nutrition', 'persist', 'finalize', name='import_error_stage'), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_record_ref', sa.String(length=255), nullable=True),
    sa.Column('menu_item_id', sa.Uuid(), nullable=True),
    sa.Column('ingredient_context', sa.String(length=255), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['data_import_id'], ['data_imports.id'], name=op.f('fk_import_errors_data_import_id_data_imports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_import_errors_menu_item_id_menu_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_errors'))
    )
    op.create_index('ix_import_errors_data_import_id', 'import_errors', ['data_import_id'], unique=False)
    op.create_index('ix_import_errors_data_import_id_severity', 'import_errors', ['data_import_id', 'severity'], unique=False)
    op.create_table('recipe_versions',
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sa.String(length=100), server_default='unknown', nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('yield_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('yield_unit', sa.String(length=50), nullable=True),
    sa.Column('servings', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_import_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['created_by_import_id'], ['data_imports.id'], name=op.f('fk_recipe_versions_created_by_import_id_data_imports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_recipe_versions_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_versions')),
    sa.UniqueConstraint('menu_item_id', 'version_no', name='uq_recipe_versions_menu_item_id_version_no')
    )
    op.create_index('uq_recipe_versions_active_per_menu_item', 'recipe_versions', ['menu_item_id'], unique=True, postgresql_where=sa.text('valid_until IS NULL'))
    op.create_index('ix_recipe_versions_menu_item_id_source_system_external_id', 'recipe_versions', ['menu_item_id', 'source_system', 'external_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_version_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('parsed_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('parsed_unit', sa.String(length=50), nullable=True),
    sa.Column('normalized_ingredient_name', sa.String(length=255), nullable=True),
    sa.Column('preparation_notes', sa.Text(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw_or_cooked', sa.Enum('raw', 'cooked', 'unknown', name='raw_or_cooked'), nullable=True),
    sa.Column('grams', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ingredient_id', sa.Uuid(), nullable=True),
    sa.Column('provider_food_id', sa.Uuid(), nullable=True),
    sa.Column('match_method', sa.Enum('source_external_id', 'provider_search', 'manual', 'fixture', 'unmatched', name='ingredient_match_method'), nullable=True),
    sa.Column('resolution_status', sa.Enum('resolved', 'needs_review', 'unsupported_quantity', 'nutrition_match_missing', 'yield_missing', 'excluded_non_nutritive', 'invalid', name='ingredient_resolution_status'), server_default='needs_review', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_recipe_ingredients_confidence_range')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_recipe_ingredients_ingredient_id_ingredients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_food_id'], ['provider_foods.id'], name=op.f('fk_recipe_ingredients_provider_food_id_provider_foods'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_versions.id'], name=op.f('fk_recipe_ingredients_recipe_version_id_recipe_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients')),
    sa.UniqueConstraint('recipe_version_id', 'line_no', name='uq_recipe_ingredients_recipe_version_id_line_no')
    )
    op.create_index('ix_recipe_ingredients_provider_food_id', 'recipe_ingredients', ['provider_food_id'], unique=False)
    op.create_index('ix_recipe_ingredients_recipe_version_id', 'recipe_ingredients', ['recipe_version_id'], unique=False)
    op.add_column('data_imports', sa.Column('requested_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('data_imports', sa.Column('records_skipped', sa.Integer(), server_default='0', nullable=False))
    op.add_column('data_imports', sa.Column('ingredients_resolved', sa.Integer(), server_default='0', nullable=False))
    op.add_column('data_imports', sa.Column('ingredients_unresolved', sa.Integer(), server_default='0', nullable=False))
    op.add_column('data_imports', sa.Column('nutrition_provided_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('data_imports', sa.Column('nutrition_calculated_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('ingredients', sa.Column('source_system', sa.String(length=100), server_default='unknown', nullable=False))
    op.create_index('uq_ingredients_institution_id_source_system_external_id', 'ingredients', ['institution_id', 'source_system', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.add_column('institutions', sa.Column('source_system', sa.String(length=100), server_default='unknown', nullable=False))
    op.create_index('uq_institutions_source_system_external_id', 'institutions', ['source_system', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.add_column('menu_items', sa.Column('source_system', sa.String(length=100), server_default='unknown', nullable=False))
    op.drop_index(op.f('uq_menu_items_institution_id_external_id'), table_name='menu_items', postgresql_where='(external_id IS NOT NULL)')
    op.create_index('uq_menu_items_institution_id_source_system_external_id', 'menu_items', ['institution_id', 'source_system', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.add_column('menu_offerings', sa.Column('source_system', sa.String(length=100), server_default='unknown', nullable=False))
    op.create_index('uq_menu_offerings_station_id_source_system_external_id', 'menu_offerings', ['station_id', 'source_system', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.add_column('nutrition_facts', sa.Column('provenance', nutrition_provenance, server_default='source_provided', nullable=False))
    op.add_column('nutrition_facts', sa.Column('is_complete', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('nutrition_facts', sa.Column('review_status', nutrition_review_status, server_default='not_required', nullable=False))
    op.add_column('nutrition_facts', sa.Column('calculation_status', calculation_status, nullable=True))
    op.add_column('nutrition_facts', sa.Column('calculation_version', sa.String(length=50), nullable=True))
    op.add_column('nutrition_facts', sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('nutrition_facts', sa.Column('recipe_version_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('uq_nutrition_facts_active_per_menu_item'), table_name='nutrition_facts', postgresql_where='(valid_until IS NULL)')
    op.create_index('uq_nutrition_facts_active_per_menu_item_provenance', 'nutrition_facts', ['menu_item_id', 'provenance'], unique=True, postgresql_where=sa.text('valid_until IS NULL'))
    op.create_foreign_key(op.f('fk_nutrition_facts_recipe_version_id_recipe_versions'), 'nutrition_facts', 'recipe_versions', ['recipe_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('stations', sa.Column('source_system', sa.String(length=100), server_default='unknown', nullable=False))
    op.create_index('uq_stations_venue_id_source_system_external_id', 'stations', ['venue_id', 'source_system', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.add_column('venues', sa.Column('source_system', sa.String(length=100), server_default='unknown', nullable=False))
    op.create_index('uq_venues_institution_id_source_system_external_id', 'venues', ['institution_id', 'source_system', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_venues_institution_id_source_system_external_id', table_name='venues', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_column('venues', 'source_system')
    op.drop_index('uq_stations_venue_id_source_system_external_id', table_name='stations', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_column('stations', 'source_system')
    op.drop_constraint(op.f('fk_nutrition_facts_recipe_version_id_recipe_versions'), 'nutrition_facts', type_='foreignkey')
    op.drop_index('uq_nutrition_facts_active_per_menu_item_provenance', table_name='nutrition_facts', postgresql_where=sa.text('valid_until IS NULL'))
    op.create_index(op.f('uq_nutrition_facts_active_per_menu_item'), 'nutrition_facts', ['menu_item_id'], unique=True, postgresql_where='(valid_until IS NULL)')
    op.drop_column('nutrition_facts', 'recipe_version_id')
    op.drop_column('nutrition_facts', 'calculated_at')
    op.drop_column('nutrition_facts', 'calculation_version')
    op.drop_column('nutrition_facts', 'calculation_status')
    op.drop_column('nutrition_facts', 'review_status')
    op.drop_column('nutrition_facts', 'is_complete')
    op.drop_column('nutrition_facts', 'provenance')
    op.drop_index('uq_menu_offerings_station_id_source_system_external_id', table_name='menu_offerings', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_column('menu_offerings', 'source_system')
    op.drop_index('uq_menu_items_institution_id_source_system_external_id', table_name='menu_items', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.create_index(op.f('uq_menu_items_institution_id_external_id'), 'menu_items', ['institution_id', 'external_id'], unique=True, postgresql_where='(external_id IS NOT NULL)')
    op.drop_column('menu_items', 'source_system')
    op.drop_index('uq_institutions_source_system_external_id', table_name='institutions', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_column('institutions', 'source_system')
    op.drop_index('uq_ingredients_institution_id_source_system_external_id', table_name='ingredients', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_column('ingredients', 'source_system')
    op.drop_column('data_imports', 'nutrition_calculated_count')
    op.drop_column('data_imports', 'nutrition_provided_count')
    op.drop_column('data_imports', 'ingredients_unresolved')
    op.drop_column('data_imports', 'ingredients_resolved')
    op.drop_column('data_imports', 'records_skipped')
    op.drop_column('data_imports', 'requested_scope')
    op.drop_index('ix_recipe_ingredients_recipe_version_id', table_name='recipe_ingredients')
    op.drop_index('ix_recipe_ingredients_provider_food_id', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('ix_recipe_versions_menu_item_id_source_system_external_id', table_name='recipe_versions')
    op.drop_index('uq_recipe_versions_active_per_menu_item', table_name='recipe_versions', postgresql_where=sa.text('valid_until IS NULL'))
    op.drop_table('recipe_versions')
    op.drop_index('ix_import_errors_data_import_id_severity', table_name='import_errors')
    op.drop_index('ix_import_errors_data_import_id', table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index('ix_provider_food_portions_provider_food_id', table_name='provider_food_portions')
    op.drop_table('provider_food_portions')
    op.drop_table('provider_foods')
    # ### end Alembic commands ###

    # Native ENUM types introduced by this revision are not dropped by the table
    # / column drops above; remove them explicitly so a downgrade leaves a clean
    # database and a subsequent re-upgrade can recreate the types.
    for enum_name in (
        "nutrition_provenance",
        "nutrition_review_status",
        "calculation_status",
        "ingredient_resolution_status",
        "ingredient_match_method",
        "raw_or_cooked",
        "import_error_severity",
        "import_error_stage",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

