"""Reusable column mixins shared by PlateWise ORM models.

These mixins centralize the repetitive column definitions described in the
architecture document (stable UUID identifiers, PlateWise-managed timestamps,
and source-change-detection metadata) so individual model modules stay focused
on their domain-specific columns and relationships.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, String, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKeyMixin:
    """Adds a stable, collision-resistant UUID primary key.

    The identifier is generated by the database (``gen_random_uuid()``, built
    into PostgreSQL 13+) with a Python-side ``uuid4`` fallback so objects have
    an id before they are flushed.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    """Adds PlateWise-managed ``created_at`` / ``updated_at`` timestamps.

    ``created_at`` records when PlateWise first stored the row; ``updated_at``
    records when PlateWise last modified it. Both are timezone-aware and
    maintained by the database.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SourceTrackingMixin:
    """Adds source-provenance and change-detection columns.

    ``source_updated_at`` is the *source system's* update timestamp (nullable,
    because many sources omit it). ``content_hash`` is a deterministic
    fingerprint of the record's meaningful fields, used to detect real content
    changes even when source timestamps are missing or unreliable.
    """

    source_updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    content_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
