"""initial platewise schema

Revision ID: 20260718_0001
Revises: 
Create Date: 2026-07-18 04:27:22.743919
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '20260718_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allergens')),
    sa.UniqueConstraint('normalized_name', name='uq_allergens_normalized_name')
    )
    op.create_table('dietary_tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dietary_tags')),
    sa.UniqueConstraint('normalized_name', name='uq_dietary_tags_normalized_name')
    )
    op.create_table('institutions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('institution_type', sa.Enum('university', 'hospital', 'corporate_campus', 'senior_living', 'government', 'other', name='institution_type'), server_default='other', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions')),
    sa.UniqueConstraint('slug', name='uq_institutions_slug')
    )
    op.create_table('data_imports',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('fixture', 'json', 'csv', 'foodpro_export', 'nutrislice_export', 'manual', 'other', name='import_source_type'), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('source_snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'completed_with_errors', 'failed', name='import_status'), server_default='pending', nullable=False),
    sa.Column('records_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_unchanged', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('raw_payload_reference', sa.String(length=1000), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_data_imports_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_imports'))
    )
    op.create_index('ix_data_imports_institution_id_started_at', 'data_imports', ['institution_id', 'started_at'], unique=False)
    op.create_table('ingredients',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_ingredients_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients')),
    sa.UniqueConstraint('institution_id', 'normalized_name', name='uq_ingredients_institution_id_normalized_name')
    )
    op.create_index('ix_ingredients_institution_id_normalized_name', 'ingredients', ['institution_id', 'normalized_name'], unique=False)
    op.create_table('venues',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('venue_type', sa.Enum('dining_hall', 'cafeteria', 'cafe', 'food_court', 'restaurant', 'other', name='venue_type'), server_default='other', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_venues_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues')),
    sa.UniqueConstraint('institution_id', 'slug', name='uq_venues_institution_id_slug')
    )
    op.create_index(op.f('ix_venues_institution_id'), 'venues', ['institution_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_serving_size', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('default_serving_unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by_import_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_import_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['created_by_import_id'], ['data_imports.id'], name=op.f('fk_menu_items_created_by_import_id_data_imports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_menu_items_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_import_id'], ['data_imports.id'], name=op.f('fk_menu_items_updated_by_import_id_data_imports'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_items'))
    )
    op.create_index('ix_menu_items_institution_id_normalized_name', 'menu_items', ['institution_id', 'normalized_name'], unique=False)
    op.create_index('uq_menu_items_institution_id_external_id', 'menu_items', ['institution_id', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.create_table('stations',
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('station_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_stations_venue_id_venues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stations')),
    sa.UniqueConstraint('venue_id', 'slug', name='uq_stations_venue_id_slug')
    )
    op.create_index(op.f('ix_stations_venue_id'), 'stations', ['venue_id'], unique=False)
    op.create_table('menu_item_aliases',
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('official', 'imported', 'user_suggested', 'manually_verified', name='alias_source_type'), server_default='imported', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_aliases_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_aliases')),
    sa.UniqueConstraint('menu_item_id', 'normalized_alias', name='uq_menu_item_aliases_menu_item_id_normalized_alias')
    )
    op.create_index('ix_menu_item_aliases_menu_item_id', 'menu_item_aliases', ['menu_item_id'], unique=False)
    op.create_index('ix_menu_item_aliases_normalized_alias', 'menu_item_aliases', ['normalized_alias'], unique=False)
    op.create_table('menu_item_allergens',
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('allergen_id', sa.Uuid(), nullable=False),
    sa.Column('declaration_type', sa.Enum('contains', 'may_contain', 'facility_warning', 'unknown', name='allergen_declaration_type'), server_default='contains', nullable=False),
    sa.Column('source_type', sa.Enum('official', 'imported', 'user_suggested', 'manually_verified', name='allergen_source_type'), server_default='official', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], name=op.f('fk_menu_item_allergens_allergen_id_allergens'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_allergens_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_allergens')),
    sa.UniqueConstraint('menu_item_id', 'allergen_id', name='uq_menu_item_allergens_menu_item_id_allergen_id')
    )
    op.create_index('ix_menu_item_allergens_allergen_id', 'menu_item_allergens', ['allergen_id'], unique=False)
    op.create_table('menu_item_dietary_tags',
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('dietary_tag_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('official', 'imported', 'user_suggested', 'manually_verified', name='dietary_tag_source_type'), server_default='official', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_menu_item_dietary_tags_confidence_range')),
    sa.ForeignKeyConstraint(['dietary_tag_id'], ['dietary_tags.id'], name=op.f('fk_menu_item_dietary_tags_dietary_tag_id_dietary_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_dietary_tags_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_dietary_tags')),
    sa.UniqueConstraint('menu_item_id', 'dietary_tag_id', name='uq_menu_item_dietary_tags_menu_item_id_dietary_tag_id')
    )
    op.create_index('ix_menu_item_dietary_tags_dietary_tag_id', 'menu_item_dietary_tags', ['dietary_tag_id'], unique=False)
    op.create_table('menu_item_ingredients',
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('preparation_notes', sa.Text(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_menu_item_ingredients_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_ingredients_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_ingredients')),
    sa.UniqueConstraint('menu_item_id', 'ingredient_id', name='uq_menu_item_ingredients_menu_item_id_ingredient_id')
    )
    op.create_index('ix_menu_item_ingredients_ingredient_id', 'menu_item_ingredients', ['ingredient_id'], unique=False)
    op.create_table('menu_offerings',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('meal_period', sa.Enum('breakfast', 'brunch', 'lunch', 'dinner', 'late_night', 'all_day', 'other', name='meal_period'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('official_status', sa.Enum('scheduled', 'available', 'unavailable', 'cancelled', 'unknown', name='offering_status'), server_default='scheduled', nullable=False),
    sa.Column('source_type', sa.Enum('fixture', 'json', 'csv', 'foodpro_export', 'nutrislice_export', 'manual', 'other', name='offering_source_type'), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_by_import_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_import_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['created_by_import_id'], ['data_imports.id'], name=op.f('fk_menu_offerings_created_by_import_id_data_imports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_offerings_menu_item_id_menu_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_menu_offerings_station_id_stations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_import_id'], ['data_imports.id'], name=op.f('fk_menu_offerings_updated_by_import_id_data_imports'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_offerings')),
    sa.UniqueConstraint('station_id', 'menu_item_id', 'service_date', 'meal_period', 'starts_at', name='uq_menu_offerings_slot', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_menu_offerings_menu_item_id_service_date', 'menu_offerings', ['menu_item_id', 'service_date'], unique=False)
    op.create_index('ix_menu_offerings_station_id_service_date_meal_period', 'menu_offerings', ['station_id', 'service_date', 'meal_period'], unique=False)
    op.create_table('nutrition_facts',
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('serving_size', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('serving_unit', sa.String(length=50), nullable=True),
    sa.Column('calories', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('carbohydrates_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('saturated_fat_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sugar_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cholesterol_mg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_type', sa.Enum('official', 'recipe_calculated', 'usda_match', 'manual', 'estimated', name='nutrition_source_type'), server_default='official', nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_import_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_import_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['created_by_import_id'], ['data_imports.id'], name=op.f('fk_nutrition_facts_created_by_import_id_data_imports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_nutrition_facts_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_import_id'], ['data_imports.id'], name=op.f('fk_nutrition_facts_updated_by_import_id_data_imports'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_facts'))
    )
    op.create_index('ix_nutrition_facts_menu_item_id_valid_from_valid_until', 'nutrition_facts', ['menu_item_id', 'valid_from', 'valid_until'], unique=False)
    op.create_index('uq_nutrition_facts_active_per_menu_item', 'nutrition_facts', ['menu_item_id'], unique=True, postgresql_where=sa.text('valid_until IS NULL'))
    op.create_table('menu_item_suggestions',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('related_offering_id', sa.Uuid(), nullable=True),
    sa.Column('proposed_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'matched', 'approved', 'rejected', 'duplicate', name='suggestion_status'), server_default='pending', nullable=False),
    sa.Column('matched_menu_item_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_menu_item_suggestions_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_suggestions_matched_menu_item_id_menu_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_offering_id'], ['menu_offerings.id'], name=op.f('fk_menu_item_suggestions_related_offering_id_menu_offerings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_menu_item_suggestions_station_id_stations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_suggestions'))
    )
    op.create_index('ix_menu_item_suggestions_institution_id_status', 'menu_item_suggestions', ['institution_id', 'status'], unique=False)
    op.create_table('offering_reports',
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('sold_out', 'not_present', 'replacement', 'available_now', 'back_in_stock', 'wrong_station', 'wrong_item', 'wrong_nutrition', 'staff_confirmed', 'other', name='report_type'), nullable=False),
    sa.Column('replacement_menu_item_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderation_status', sa.Enum('active', 'retracted', 'flagged', 'rejected', 'confirmed', name='moderation_status'), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['menu_offerings.id'], name=op.f('fk_offering_reports_offering_id_menu_offerings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replacement_menu_item_id'], ['menu_items.id'], name=op.f('fk_offering_reports_replacement_menu_item_id_menu_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offering_reports'))
    )
    op.create_index('ix_offering_reports_offering_id_reported_at', 'offering_reports', ['offering_id', 'reported_at'], unique=False)
    op.create_index('ix_offering_reports_reporter_id_offering_id', 'offering_reports', ['reporter_id', 'offering_id'], unique=False)
    op.create_index('uq_offering_reports_active_reporter_category', 'offering_reports', ['offering_id', 'reporter_id', 'report_type'], unique=True, postgresql_where=sa.text("moderation_status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_offering_reports_active_reporter_category', table_name='offering_reports', postgresql_where=sa.text("moderation_status = 'active'"))
    op.drop_index('ix_offering_reports_reporter_id_offering_id', table_name='offering_reports')
    op.drop_index('ix_offering_reports_offering_id_reported_at', table_name='offering_reports')
    op.drop_table('offering_reports')
    op.drop_index('ix_menu_item_suggestions_institution_id_status', table_name='menu_item_suggestions')
    op.drop_table('menu_item_suggestions')
    op.drop_index('uq_nutrition_facts_active_per_menu_item', table_name='nutrition_facts', postgresql_where=sa.text('valid_until IS NULL'))
    op.drop_index('ix_nutrition_facts_menu_item_id_valid_from_valid_until', table_name='nutrition_facts')
    op.drop_table('nutrition_facts')
    op.drop_index('ix_menu_offerings_station_id_service_date_meal_period', table_name='menu_offerings')
    op.drop_index('ix_menu_offerings_menu_item_id_service_date', table_name='menu_offerings')
    op.drop_table('menu_offerings')
    op.drop_index('ix_menu_item_ingredients_ingredient_id', table_name='menu_item_ingredients')
    op.drop_table('menu_item_ingredients')
    op.drop_index('ix_menu_item_dietary_tags_dietary_tag_id', table_name='menu_item_dietary_tags')
    op.drop_table('menu_item_dietary_tags')
    op.drop_index('ix_menu_item_allergens_allergen_id', table_name='menu_item_allergens')
    op.drop_table('menu_item_allergens')
    op.drop_index('ix_menu_item_aliases_normalized_alias', table_name='menu_item_aliases')
    op.drop_index('ix_menu_item_aliases_menu_item_id', table_name='menu_item_aliases')
    op.drop_table('menu_item_aliases')
    op.drop_index(op.f('ix_stations_venue_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index('uq_menu_items_institution_id_external_id', table_name='menu_items', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index('ix_menu_items_institution_id_normalized_name', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_venues_institution_id'), table_name='venues')
    op.drop_table('venues')
    op.drop_index('ix_ingredients_institution_id_normalized_name', table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index('ix_data_imports_institution_id_started_at', table_name='data_imports')
    op.drop_table('data_imports')
    op.drop_table('institutions')
    op.drop_table('dietary_tags')
    op.drop_table('allergens')
    # ### end Alembic commands ###

    # Native ENUM types are created implicitly with their owning tables but are
    # not dropped by table drops; remove them explicitly so a downgrade leaves a
    # clean database and a subsequent upgrade can recreate the types.
    for enum_name in (
        "institution_type",
        "import_source_type",
        "import_status",
        "venue_type",
        "alias_source_type",
        "allergen_declaration_type",
        "allergen_source_type",
        "dietary_tag_source_type",
        "meal_period",
        "offering_status",
        "offering_source_type",
        "nutrition_source_type",
        "suggestion_status",
        "report_type",
        "moderation_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

